version: "3.8"

services:
  document-server:
    container_name: document-server
    image: onlyoffice/documentserver:7.3.3.50
    expose:
      - "80"
    environment:
      - JWT_SECRET=your-256-bit-secret

  example:
    container_name: example
    build:
      context: .
      target: example
    volumes:
      - static:/srv/static
    expose:
      - "80"
    environment:
      - DOCUMENT_SERVER_PRIVATE_URL=http://proxy:3000/
      - DOCUMENT_SERVER_PUBLIC_URL=http://localhost:3000/
      - EXAMPLE_URL=http://proxy:8080/
      - JWT_SECRET=your-256-bit-secret
      - PORT=80

  proxy:
    container_name: proxy
    build:
      context: .
      target: proxy
    volumes:
      - static:/srv/static
    ports:
      - "8080:8080"
      - "3000:3000"

volumes:
  static:
