name: Release

on:
  push:
    branches: [master,main]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install Zip
        run: sudo apt-get install zip
      - name: Get Info
        run: |
          echo "version=$(grep -Eo '[0-9]+(\.[0-9]+)+' CHANGELOG.md | head -n 1)" >> $GITHUB_OUTPUT
        id: info
      - name: Generate Changelog
        run: |
          awk '/## [0-9]/{p++} p; /## [0-9]/{if (p > 1) exit}' CHANGELOG.md | awk 'NR>2 {print last} {last=$0}' > RELEASE.md
      - name: Build Nodejs Artifact
        run: |
          cd ${{ github.workspace }}
          cwd=$(pwd)
          git submodule update --init --recursive
          cd ./web/documentserver-example/nodejs
          mkdir -p ./'Node.js Example'
          rsync -av --exclude='Node.js Example' ./ ./'Node.js Example'
          cd ./'Node.js Example'/public/assets
          rm -rf ./.git/
          rm .git
      - name: Pack Artifacts
        run: |
          cd ${{ github.workspace }}/web/documentserver-example/nodejs
          zip -r Node.js.Example.zip ./'Node.js Example'
      - name: Create Release
        uses: ncipollo/release-action@v1
        id: create_release
        with:
          bodyFile: RELEASE.md
          artifacts: "
            ${{ github.workspace }}/web/documentserver-example/nodejs/Node.js.Example.zip,
          "
          tag: v${{ steps.info.outputs.version }}