name: Change copyright

on:
  push:

jobs:
  copyright:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: REUSE SPDX SBOM
        uses: fsfe/reuse-action@v3
        with:
          args: spdx
